### ISSUE TITLE
Add a date trigger for the events

### ISSUE THREAD

**Issue by benpaddlejones** [MerrylandsHighSchool/carnival#8]
//year, month 0-11, date, hour, min 
if(Date(2019, 4, 15, 25, 0).getTime() > Date.now();

**Comment by pleasework23** [comment]
easy

**Comment by benpaddlejones** [comment]
correction: 
//year, month 0-11, date, hour, min
if(new Date(2019, 4, 9, 16, 21).getTime() < Date.now()) {
	i = 1;
}

**Comment by VeldenBergonia** [comment]
Requires testing.
